TOTAL_INSTANCES_SUBNET = 2

DEPLOY_CLIENT = "false"
TOTAL_CPU_CLIENT = "4096"
TOTAL_MEMORY_CLIENT = "16384"

DEPLOY_WORKER = "true"
TOTAL_CPU_WORKER = "4096"
TOTAL_MEMORY_WORKER = "16384"
#LAUNCH_TYPE_WORKER="EC2"

DEPLOY_OPTIMIST = "false"
TOTAL_CPU_OPTIMIST = "4096"
TOTAL_MEMORY_OPTIMIST = "16384"

DEPLOY_PROPOSER = "false"
TOTAL_CPU_PROPOSER = "4096"
TOTAL_MEMORY_PROPOSER = "16384"

DEPLOY_BLOCKCHAIN = "false"
TOTAL_CPU_BLOCKCHAIN = "4096"
TOTAL_MEMORY_BLOCKCHAIN = "16384"
