version: '3.5'
# Tests nightfall-client
services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app/src/
      - ./test:/app/test/
      - mongodb:/app/mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    command: ['npm', 'test']
  worker:
    image: docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates_worker:1.0.2
    volumes:
      - circuits:/app/circuits
volumes:
  mongodb:
  circuits:
