version: '3.5'
# Use this script for running up nightfall_3 in 'developer' mode with local
# bindings.  See the readme for more information.
services:
  proposer:
    image: ghcr.io/eyblockchain/nightfall3-proposer:latest
    networks:
      - nightfall_network
    environment:
      OPTIMIST_HOST: optimist1
      OPTIMIST_WS_PORT: 8080
      OPTIMIST_PORT: 80
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      CLIENT_HOST: client1
      CLIENT_PORT: 80
      PROPOSER_PORT: 8080
      PROPOSER_HOST: proposer
