version: '3.5'
services:
  client1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      FROM_ADDRESS: "0x10B111737de4c659C2F2285A04F66b5Af3758058"
      ETH_NETWORK: edge

  client2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      ETH_NETWORK: edge
      FROM_ADDRESS: "0x10B111737de4c659C2F2285A04F66b5Af3758058"

  deployer:
    environment:
      # ETH_NETWORK sets the network selected by Truffle from truffle-config.js
      # startup routines will wait for a blockchain client to be reachable on this network
      BLOCKCHAIN_WS_HOST: host.docker.internal
      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      FROM_ADDRESS: "0x10B111737de4c659C2F2285A04F66b5Af3758058"
      ETH_PRIVATE_KEY: "ca9271cf002321d6d366f7f347931a3024116f4bb550db9b32893cd6cfb6bf00"
      ETH_NETWORK: edge

  optimist1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      FROM_ADDRESS: "0x10B111737de4c659C2F2285A04F66b5Af3758058"
      ETH_NETWORK: edge

  optimist2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      FROM_ADDRESS: "0x10B111737de4c659C2F2285A04F66b5Af3758058"
      ETH_NETWORK: edge
