version: '3.5'
# Tests nightfall-client
services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - build:/app/build
      - mongodb:/app/mongodb
    networks:
      - nightfall_network
    ports:
      - 27017:27017
      - 8080:80
    depends_on:
      - deployer
      - worker
      - ganache
      - timber
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      LOG_LEVEL: silly
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
    command: ['npm', 'start']

  worker:
    # image: docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates_worker:1.0.8
    build:
      dockerfile: Dockerfile
      context: ../zokrates-worker
    volumes:
      - type: volume
        source: proving_files
        target: /app/output/
      - type: bind
        source: ../nightfall-deployer/circuits
        target: /app/circuits/
    depends_on:
      - deployer
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: info

    # Temporary container to deploy contracts and circuits and populate volumes
  deployer:
    #image: docker.pkg.github.com/eyblockchain/nightfall-deployer/nightfall_deployer:1.1.0
    build:
      context: ../nightfall-deployer/
      dockerfile: Dockerfile
    depends_on:
      - ganache
    volumes:
      - type: volume
        source: build
        target: /app/build/
      - type: bind
        source: ../nightfall-deployer/contracts
        target: /app/contracts/
      - type: bind
        source: ../nightfall-deployer/circuits
        target: /app/circuits/
      - type: bind
        source: ../nightfall-deployer/src
        target: /app/src/
      - type: bind
        source: ../nightfall-deployer/config
        target: /app/config/
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: debug
      ETH_NETWORK: ganache
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545

  # The openethereum (Parity) client, containing required precompiles
  ganache:
    image: trufflesuite/ganache-cli:latest
    command:
      ganache-cli --accounts=10 --defaultBalanceEther=1000 --gasLimit=12500000 --deterministic
    ports:
      - '8545:8545'
    networks:
      - nightfall_network

  # Timber service, configured for nightfall
  timber:
    build:
      dockerfile: Dockerfile
      context: ../nightfall-timber
    depends_on:
      - ganache
      - deployer
      - timber-database
    networks:
      - nightfall_network
    volumes:
      - type: volume
        source: build
        target: /app/build/
    restart: on-failure
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      MONGO_HOST: timber-database
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      HASH_TYPE: mimc
      LOG_LEVEL: debug
      AUTOSTART: Shield

  #The database storing the merkle tree
  #At present Timber seems to need a specially configured db.  If we can fix
  #that, we can run it on a vanilla mongo instance
  timber-database:
    image: docker.pkg.github.com/eyblockchain/timber-mongo/timber_mongo:73c12fc8bd35d4cab739c836b738b416f6db64ba
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - timber-database-volume:/data/db
    networks:
      - nightfall_network

volumes:
  mongodb:
  #circuits:
  proving_files:
  build:
  timber-database-volume:

networks:
  nightfall_network:
