version: '3.5'
# Use this script for running up nightfall_3 in 'developer' mode with local
# bindings and expects a pre-existing blockchain client on localhost.
# Use it as an override file for docker-compose.yml
# See the readme for more information.
services:

  client1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

  client2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal
      AUTOSTART_RETRIES: 100

  deployer:
    environment:
      LOG_LEVEL: debug
      # ETH_NETWORK sets the network selected by Truffle from truffle-config.js
      # startup routines will wait for a blockchain client to be reachable on this network
      ETH_NETWORK: development
      BLOCKCHAIN_WS_HOST: host.docker.internal

  # Timber service, configured for nightfall
  timber1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal
      LOG_LEVEL: debug

  optimist1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

  timber2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal
      AUTOSTART_RETRIES: 100
      # LOG_LEVEL: debug

  optimist2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal
      AUTOSTART_RETRIES: 100
