version: '3.5'
# Tests nightfall-client
services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - build:/app/build
      - mongodb:/app/mongodb
    networks:
      - nightfall_network
    ports:
      - 27017:27017
      - 8080:80
    depends_on:
      - deployer
      - worker
      - ganache
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      LOG_LEVEL: silly
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
    command: ['npm', 'start']

  worker:
    # image: docker.pkg.github.com/eyblockchain/zokrates-worker/zokrates_worker:1.0.8
    build:
      dockerfile: Dockerfile
      context: ../zokrates-worker
    volumes:
      - type: volume
        source: proving_files
        target: /app/output/
      - type: volume
        source: circuits
        target: /app/circuits/
    depends_on:
      - deployer
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: info

    # Temporary container to deploy contracts and circuits and populate volumes
  deployer:
    image: docker.pkg.github.com/eyblockchain/nightfall-deployer/nightfall_deployer:1.1.0
    #build:
    #  context: ../nightfall-deployer/
    #  dockerfile: Dockerfile
    depends_on:
      - ganache
    volumes:
      - type: volume
        source: build
        target: /app/build/
      #    - type: bind
      #      source: ../nightfall-deployer/contracts
      #      target: /app/contracts/
      - type: volume
        source: circuits
        target: /app/circuits/
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: debug
      ETH_NETWORK: ganache
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545

  # The openethereum (Parity) client, containing required precompiles
  ganache:
    image: trufflesuite/ganache-cli:latest
    command:
      ganache-cli --accounts=10 --defaultBalanceEther=1000 --gasLimit=12500000 --deterministic
    ports:
      - '8545:8545'
    networks:
      - nightfall_network

volumes:
  mongodb:
  circuits:
  proving_files:
  build:

networks:
  nightfall_network:
