version: '3.5'
services:
   wallet-test:
      build:
        dockerfile: Dockerfile
        context: ./wallet
      networks:
        - nightfall_network
      user: apps
      ports:
        - 5900:5900
        - 3010:3010
      privileged: true
      environment:
          - VNC_SERVER_PASSWORD=password
          - RUN_SELENIUM_TESTS=${RUN_SELENIUM_TESTS}
          - ENABLE_VNC_SERVER=${ENABLE_VNC_SERVER}
       
