version: '3.5'
# Use this script for running up a standalone Geth private network, accessed
# through localhost. It is a complete file, and not an override.
services:
  bootnode:
    image: ethereum/client-go:alltools-stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
    networks:
      geth_network:
        # fixed IP because the enode can't use a dns name
        ipv4_address: 172.16.239.10
    command: bootnode --nodekey=setup/node.key

  blockchain:
    image: ethereum/client-go:stable
    ports:
      - 8546:8546
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: volume
        source: geth1-chain
        target: /data
    networks:
      geth_network:
    entrypoint: /setup/entrypoint.sh
    command: --ws.port 8546 --ws --ws.origins '*' --ws.addr 0.0.0.0 --verbosity 3 --rpc.txfeecap 0

  blockchain-miner1:
    image: ethereum/client-go:stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: volume
        source: geth-miner-chain1
        target: /data
      - type: volume
        source: dag1
        target: /dag
    networks:
      geth_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --ws.port 8546 --ws --ws.origins '*' --ws.addr 0.0.0.0 --mine --verbosity 3 --rpc.txfeecap 0

networks:
  geth_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1

volumes:
  geth1-chain:
  geth-miner-chain1:
  dag1:
