version: '3.5'
# Use this script for running up nightfall_3 in 'developer' mode with local
# bindings.  See the readme for more information.
services:
  bootnode:
    image: ethereum/client-go:alltools-stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
    networks:
      nightfall_network:
        # fixed IP because the enode can't use a dns name
        ipv4_address: 172.16.238.10
    command:
      bootnode --nodekey=setup/node.key

  blockchain1:
    image: ethereum/client-go:stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: volume
        source: geth1-chain
        target: /data
    networks:
      nightfall_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --ws.port 8546 --ws --ws.origins '*' --ws.addr 0.0.0.0 --verbosity 2

  blockchain2:
    image: ethereum/client-go:stable
    ports:
      - 8547:8546
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: volume
        source: geth2-chain
        target: /data
    networks:
      nightfall_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --ws.port 8546 --ws --ws.origins '*' --ws.addr 0.0.0.0 --verbosity 2

  blockchain-miner1:
    image: ethereum/client-go:stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: volume
        source: geth-miner-chain1
        target: /data
      - type: volume
        source: dag1
        target: /dag
    networks:
      nightfall_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --ws.port 8546 --ws --ws.origins '*' --ws.addr 0.0.0.0 --mine --verbosity 2

  blockchain-miner2:
    image: ethereum/client-go:stable
    volumes:
      - type: bind
        source: ./config/geth
        target: /setup
      - type: volume
        source: geth-miner-chain2
        target: /data
      - type: volume
        source: dag2
        target: /dag
    networks:
      nightfall_network:
    entrypoint: /setup/entrypoint.sh
    command:
      --ws.port 8546 --ws --ws.origins '*' --ws.addr 0.0.0.0 --mine --verbosity 2

  timber:
    environment:
      AUTOSTART_RETRIES: 300

  deployer:
    environment:
      AUTOSTART_RETRIES: 300

  optimist:
    environment:
      AUTOSTART_RETRIES: 300

  client:
    environment:
      AUTOSTART_RETRIES: 300

volumes:
  geth1-chain:
  geth2-chain:
  geth-miner-chain1:
  dag1:
  geth-miner-chain2:
  dag2:
