version: '3.5'
# Use this script for running up nightfall_3 in 'ropsten' mode with local
# Use it as an override file for docker-compose.yml
# See the readme for more information.
services:
  client1:
    environment:
      BLOCKCHAIN_URL: 'wss://ropsten.infura.io/ws/v3/${INFURA_PROJECT_ID}'
      USE_INFURA: 'true'
      AUTOSTART_RETRIES: 500
      INFURA_PROJECT_SECRET: $INFURA_PROJECT_SECRET

  client2:
    environment:
      BLOCKCHAIN_URL: 'wss://ropsten.infura.io/ws/v3/${INFURA_PROJECT_ID}'
      USE_INFURA: 'true'
      AUTOSTART_RETRIES: 500
      INFURA_PROJECT_SECRET: $INFURA_PROJECT_SECRET

  deployer:
    environment:
      # ETH_NETWORK sets the network selected by Truffle from truffle-config.js
      # startup routines will wait for a blockchain client to be reachable on this network
      ETH_NETWORK: ropsten
      BLOCKCHAIN_URL: 'wss://:${INFURA_PROJECT_SECRET}@ropsten.infura.io/ws/v3/${INFURA_PROJECT_ID}'
      USE_INFURA: 'true'
      FROM_ADDRESS: '0x29100E7E3dA6654BF63d9E7804ADe518aCc5AaA5'
      ETH_PRIVATE_KEY: $ETH_PRIVATE_KEY
      INFURA_PROJECT_SECRET: $INFURA_PROJECT_SECRET

  optimist1:
    environment:
      BLOCKCHAIN_URL: 'wss://ropsten.infura.io/ws/v3/${INFURA_PROJECT_ID}'
      USE_INFURA: 'true'
      AUTOSTART_RETRIES: 500
      INFURA_PROJECT_SECRET: $INFURA_PROJECT_SECRET

  optimist2:
    environment:
      BLOCKCHAIN_URL: 'wss://ropsten.infura.io/ws/v3/${INFURA_PROJECT_ID}'
      USE_INFURA: 'true'
      AUTOSTART_RETRIES: 500
      INFURA_PROJECT_SECRET: $INFURA_PROJECT_SECRET
