version: '3.5'
services:
  client1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      FROM_ADDRESS: "0x6EF22eb79a246E8012414387d9d4319d3A193414"
      ETH_NETWORK: edge

  client2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      ETH_NETWORK: edge
      FROM_ADDRESS: "0x6EF22eb79a246E8012414387d9d4319d3A193414"

  deployer:
    environment:
      # ETH_NETWORK sets the network selected by Truffle from truffle-config.js
      # startup routines will wait for a blockchain client to be reachable on this network
      BLOCKCHAIN_WS_HOST: host.docker.internal
      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      FROM_ADDRESS: "0x6EF22eb79a246E8012414387d9d4319d3A193414"
      ETH_PRIVATE_KEY: "d609df66fe73fb4dda166a36db35637a070da0a739a65237c7b4e65ca9713a6d"
      ETH_NETWORK: edge

  optimist1:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      FROM_ADDRESS: "0x6EF22eb79a246E8012414387d9d4319d3A193414"
      ETH_NETWORK: edge

  optimist2:
    environment:
      BLOCKCHAIN_WS_HOST: host.docker.internal

      BLOCKCHAIN_PORT: 10002
      BLOCKCHAIN_PATH: /ws
      USE_EXTERNAL_NODE: 'true'
      AUTOSTART_RETRIES: 600
      FROM_ADDRESS: "0x6EF22eb79a246E8012414387d9d4319d3A193414"
      ETH_NETWORK: edge
