version: '3.5'
# Use this script for running up nightfall_3 in 'developer' mode with local
# bindings.  See the readme for more information.
services:
  client1:
    build:
      dockerfile: Dockerfile
      context: ./nightfall-client
    volumes:
      - type: bind
        source: ./nightfall-client/src
        target: /app/src
      - type: bind
        source: ./common-files
        target: /common-files
      - type: bind
        source: ./config/default.js
        target: /app/config/default.js

  client2:
    build:
      dockerfile: Dockerfile
      context: ./nightfall-client
    volumes:
      - type: bind
        source: ./nightfall-client/src
        target: /app/src
      - type: bind
        source: ./common-files
        target: /common-files
      - type: bind
        source: ./config/default.js
        target: /app/config/default.js

  worker:
    #  image: 3800decac71d
    build:
      dockerfile: Dockerfile
      context: ./zokrates-worker
    volumes:
      - type: bind
        source: ./nightfall-deployer/circuits
        target: /app/circuits/
      - type: bind
        source: ./zokrates-worker/src
        target: /app/src/
      - type: bind
        source: ./config/default.js
        target: /app/config/default.js
  deployer:
    #image: docker.pkg.github.com/eyblockchain/nightfall-deployer/nightfall_deployer:1.1.0

    build:
      context: ./nightfall-deployer
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./nightfall-deployer/contracts
        target: /app/contracts/
      - type: bind
        source: ./nightfall-deployer/circuits
        target: /app/circuits/
      - type: bind
        source: ./nightfall-deployer/src
        target: /app/src/
      - type: bind
        source: ./common-files
        target: /common-files
      - type: bind
        source: ./config/default.js
        target: /app/config/default.js
      - type: bind
        source: ./nightfall-deployer/migrations
        target: /app/migrations
      - type: bind
        source: ./nightfall-deployer/truffle-config.js
        target: /app/truffle-config.js
      - type: bind
        source: ./nightfall-deployer/entrypoint.sh
        target: /app/entrypoint.sh

  optimist1:

    build:
      context: ./nightfall-optimist
    volumes:

      - type: bind
        source: ./nightfall-optimist/src
        target: /app/src
      - type: bind
        source: ./common-files
        target: /common-files
      - type: bind
        source: ./config/default.js
        target: /app/config/default.js
  optimist2:

    build:
      context: ./nightfall-optimist
    volumes:

      - type: bind
        source: ./nightfall-optimist/src
        target: /app/src
      - type: bind
        source: ./common-files
        target: /common-files
      - type: bind
        source: ./config/default.js
        target: /app/config/default.js
