version: '3.5'
# Use this script for running up nightfall_3 with images
# If you replace the main docker-compose with this file, it should work!
services:
  client1:
    image: ghcr.io/eyblockchain/nightfall3-client:latest
    volumes:
      - type: volume
        source: build
        target: /app/build
      - type: volume
        source: mongodb1
        target: /app/mongodb
    networks:
      - nightfall_network
    ports:
      - 27017:27017
      - 8080:80
    depends_on:
      - deployer
      - worker
      - timber1
      - rabbitmq1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      LOG_LEVEL: debug
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      ZOKRATES_WORKER_HOST: worker
      RABBITMQ_HOST: amqp://rabbitmq1
      RABBITMQ_PORT: 5672
      TIMBER_HOST: timber1
      TIMBER_PORT: 80
      ENABLE_QUEUE: 1
      OPTIMIST_HOST: optimist1
      OPTIMIST_PORT: 80
      USE_STUBS: 'false' # make sure this flag is the same as in deployer service
    command: ['npm', 'run', 'dev']

  client2:
    image: ghcr.io/eyblockchain/nightfall3-client:latest
    volumes:
      - type: volume
        source: build
        target: /app/build
    networks:
      - nightfall_network
    ports:
      - 27018:27017
      - 8084:80
    depends_on:
      - deployer
      - worker
      - timber2
      - rabbitmq2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      LOG_LEVEL: error
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      ZOKRATES_WORKER_HOST: worker
      RABBITMQ_HOST: amqp://rabbitmq2
      RABBITMQ_PORT: 5672
      TIMBER_HOST: timber2
      TIMBER_PORT: 80
      ENABLE_QUEUE: 1
      OPTIMIST_HOST: optimist2
      OPTIMIST_PORT: 80
      USE_STUBS: 'false' # make sure this flag is the same as in deployer service
    command: ['npm', 'run', 'dev']

  worker:
    image: ghcr.io/eyblockchain/nightfall3-worker
    volumes:
      - type: volume
        source: ./proving_files
        target: /app/output/
    depends_on:
      - deployer
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: info

    # Temporary container to deploy contracts and circuits and populate volumes
  deployer:
    image: ghcr.io/eyblockchain/nightfall3-deployer
    volumes:
      - type: volume
        source: build
        target: /app/build/
      # - type: bind
      #   source: ./config/default.js
      #   target: /app/config/default.js
    networks:
      - nightfall_network
    environment:
      LOG_LEVEL: debug
      # ETH_NETWORK sets the network selected by Truffle from truffle-config.js
      # startup routines will wait for a blockchain client to be reachable on this network
      ETH_NETWORK: blockchain1
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      ZOKRATES_WORKER_HOST: worker
      # TIMBER_HOST: timber1
      # TIMBER_PORT: 80
      USE_STUBS: 'false'

  # Timber service, configured for nightfall
  timber1:
    build:
      dockerfile: Dockerfile
      context: ./timber
    restart: on-failure
    depends_on:
      - deployer
      - timber-database1
    networks:
      - nightfall_network
    ports:
      - 8083:80
    volumes:
      - type: volume
        source: build
        target: /app/build/
      - type: bind
        source: ./timber/src
        target: /app/src/
      - type: bind
        source: ./config/timber.js
        target: /app/config/default.js
      - type: bind
        source: ./timber/entrypoint.sh
        target: /app/entrypoint.sh
    environment:
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      MONGO_HOST: timber-database1
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      HASH_TYPE: mimc
      LOG_LEVEL: info
      AUTOSTART: enabled

  # Timber service, configured for nightfall
  timber2:
    build:
      dockerfile: Dockerfile
      context: ./timber
    restart: on-failure
    depends_on:
      - deployer
      - timber-database2
    networks:
      - nightfall_network
    ports:
      - 8087:80
    volumes:
      - type: volume
        source: build
        target: /app/build/
      - type: bind
        source: ./timber/src
        target: /app/src/
      - type: bind
        source: ./config/timber.js
        target: /app/config/default.js
    environment:
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      MONGO_HOST: timber-database2
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      HASH_TYPE: mimc
      LOG_LEVEL: error
      AUTOSTART: enabled

  #The database storing the merkle tree
  timber-database1:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - type: volume
        source: timber-database-volume1
        target: /data/db
    networks:
      - nightfall_network

  #The database storing the merkle tree
  timber-database2:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - type: volume
        source: timber-database-volume2
        target: /data/db
    networks:
      - nightfall_network

  rabbitmq1:
    image: rabbitmq
    ports:
      - '15674:15674'
      - '5672:5672'
    networks:
      - nightfall_network

  rabbitmq2:
    image: rabbitmq
    ports:
      - '15675:15674'
      - '5673:5672'
    networks:
      - nightfall_network

  optimist1:
    image: ghcr.io/eyblockchain/nightfall3-optimist:latest
    depends_on:
      - timber1
      - deployer
    networks:
      - nightfall_network
    ports:
      - 8081:80
      # websocket port for Optimist is on localhost:8082
      - 8082:8080
    volumes:
      - type: volume
        source: build
        target: /app/build/
    environment:
      WEBSOCKET_PORT: 8080
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      HASH_TYPE: mimc
      LOG_LEVEL: debug
      IS_CHALLENGER: 'true'
      TRANSACTIONS_PER_BLOCK: ${TRANSACTIONS_PER_BLOCK:-2}
      TIMBER_HOST: timber1
      TIMBER_PORT: 80
    command: ['npm', 'run', 'dev']

  optimist2:
    image: ghcr.io/eyblockchain/nightfall3-optimist:latest
    depends_on:
      - timber2
      - deployer
    networks:
      - nightfall_network
    ports:
      - 8085:80
      # websocket port for Optimist is on localhost:8086
      - 8086:8080
    volumes:
      - type: volume
        source: build
        target: /app/build/
      # - type: bind
    environment:
      WEBSOCKET_PORT: 8080
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      HASH_TYPE: mimc
      LOG_LEVEL: error
      IS_CHALLENGER: 'true'
      TRANSACTIONS_PER_BLOCK: ${TRANSACTIONS_PER_BLOCK:-2}
      TIMBER_HOST: timber2
      TIMBER_PORT: 80
    command: ['npm', 'run', 'dev']

volumes:
  mongodb1:
  mongodb2:
  proving_files:
  build:
  timber-database-volume1:
  timber-database-volume2:

networks:
  nightfall_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
