#! /bin/bash
# This script will start a private gth blockchain with two miners and two node.
# The two nodes expose ws:// ports on :8546 and :8547

usage()
{
  echo "Usage:"
  echo "  -s or --start; to start a two-node private geth blockchain"
  echo "  -d or --down; to shut the network down and delete volumes"
  echo "  -p or --pause; to pause the network (useful if you want the CPU for something else for a bit)"
  echo "  -u or --unpause; to un-pause the network"
  echo "  -i or --import; to import geth state"
  echo "  -l or --logs; start logging output"
  echo "  -h or --help; prints this message"
}

FILE="docker/docker-compose.standalone.geth.yml"
NAME="geth"

# select a Geth or Ganache client
if [ "$1" == "" ]; then
  usage
  exit 1
fi
case $1 in
    -s | --start )          # Clean previous geth volumes
                            sudo rm -rf config/geth/data/
                            mkdir -p config/geth/data
                            mkdir -p config/geth/data/dag1
                            mkdir -p config/geth/data/geth1-chain
                            mkdir -p config/geth/data/geth-miner-chain1
                            docker-compose -f $FILE -p $NAME up -d
                            ;;
    -d | --down )           docker-compose -f $FILE -p $NAME down -v --remove-orphans -t 1
                            ;;
    -p | --pause )          docker-compose -f $FILE -p $NAME pause
                            ;;
    -u | --unpause )        docker-compose -f $FILE -p $NAME unpause
                            ;;
    -i | --import )         # Stop geth and restart with backup data
                            shift
                            if [ -z "${1}" ]; then
                              echo "Missing import folder"
                              exit 1
                            fi
                            BACKUP_FOLDER=backup/$1
                            if [ ! -d ${BACKUP_FOLDER} ]; then
                              echo "$BACKUP_FOLDER doesnt exist"
                              exit 1
                            fi
                            docker-compose -f $FILE -p $NAME down -v --remove-orphans -t 1
                            sleep 5
                            sudo rm -rf config/geth/data
                            sudo cp -R ./${BACKUP_FOLDER}/geth/data ./config/geth
                            docker-compose -f $FILE -p $NAME up -d
                            ;;
    -l | --logs )           docker-compose -f $FILE -p $NAME logs -f
                            ;;
    -h | --help )           usage
                            ;;
    * )                     usage
                            exit 1
esac
