#! /bin/bash

usage()
{
  echo "Usage:"
  echo "./import-nightfall <backup folder>"
}

# select a folder to backup state
if [ -z "$1" ]; then
  usage
  exit 1
fi

BACKUP_FOLDER=backup/${1}
if [ ! -d "${BACKUP_FOLDER}" ]; then
  echo "${BACKUP_FOLDER} doesnt exist"
  exit 1
fi

DEPLOYER=$(docker ps | grep nightfall_3-deployer | awk '{print $1}')
docker stop $DEPLOYER


WORKER=$(docker ps | grep nightfall_3-worker-1 | awk '{print $1}')
OPTIMIST=$(docker ps | grep  nightfall_3-optimist-1| awk '{print $1}')

docker cp ./${BACKUP_FOLDER}/output $WORKER:/app/output/ 
docker cp ./${BACKUP_FOLDER}/build/* $OPTIMIST:/app/build/

mongorestore ./${BACKUP_FOLDER}/optimist_db
mongorestore ./${BACKUP_FOLDER}/client_db