#! /bin/bash

## Usage
# ./proposer [OPTIONAL ARGUMENTS]
# OPTIONAL_ARGUMENTS:
#  --environment : test environment (such us localhost, docker, testnet). If no argument given
#     proposer is launched in localhost environment

/usr/bin/env node cli/src/proposer.mjs "${@:1}"
