#! /bin/bash

## Usage
# ./proposer [OPTIONAL ARGUMENTS]
# OPTIONAL_ARGUMENTS:
#  --environment : test environment (such us localhost, docker, testnet). If no argument given
#     proposer is launched in localhost environment
#  --proposerUrl: API is launched at Url. 
#  --proposerPort: API is launched at this port. If not provided, default port 8100 is selected

/usr/bin/env node cli/src/proposer/proposer.mjs "${@:1}"
