#! /bin/bash
docker-compose down --remove-orphans
docker volume rm nightfall_3_timber-database-volume
docker volume rm nightfall_3_mongodb
docker volume rm nightfall_3_build
docker-compose up deployer -d
docker-compose up
