version: '3.5'
# Use this script for making an adversary service
services:
  adversary:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      dockerfile: docker/optimist.Dockerfile
      context: ..
    depends_on:
      - mongodb-adversary
    networks:
      - nightfall_network
    ports:
      - 8088:80
      # websocket port for adversary is on localhost:8082
      - 8089:8080
    volumes:
      - type: volume
        source: build
        target: /app/build/
      - type: bind
        source: ../test/adversary/nightfall-adversary/src
        target: /app/src
      - type: bind
        source: ../common-files
        target: /common-files
      - type: bind
        source: ../config/default.js
        target: /app/config/default.js
    environment:
      WEBSOCKET_PORT: 8080
      BLOCKCHAIN_WS_HOST: host.docker.internal
      BLOCKCHAIN_PORT: 8546
      MONGO_URL: mongodb://mongodb-adversary:27017
      HASH_TYPE: poseidon
      LOG_LEVEL: debug
      # right now it doesn't matter what is IS_CHALLENGER flag's value is because
      # optimist container state-sync code start challenges at time of startup
      # by calling startMakingChallenges() function
      # Also we don't want adversary who create bad block to be challenger as well
      # this bit of code logic is updated in test/adversary.test.mjs by making challenger
      # wbsockeet client to connect to optimist container instead of adversary
      IS_CHALLENGER: 'false'
      NONSTOP_QUEUE_AFTER_INVALID_BLOCK: 'false'
      TRANSACTIONS_PER_BLOCK: ${TRANSACTIONS_PER_BLOCK:-2}
      AUTOSTART_RETRIES: 600
      BAD_BLOCK_SEQUENCE: ${BAD_BLOCK_SEQUENCE}
      BAD_TX_SEQUENCE: ${BAD_TX_SEQUENCE}
    command: ['npm', 'run', 'dev']

  mongodb-adversary:
    image: mongo:4.4.1-bionic
    hostname: mongodb-adversary
    # ports:
    #   - 27018:27017
    networks:
      - nightfall_network
    volumes:
      - type: volume
        source: mongodb-adversary-db
        target: /data/db

volumes:
  mongodb-adversary-db:
