version: '3.5'
# Use this script for running up nightfall_3 in 'developer' mode with local
# bindings and using a Hardhat netwrok private blockchain.  See the readme for more information.
# It acts as an override file for docker-compose.yml
services:
  blockchain:
    build:
      dockerfile: docker/hardhat.Dockerfile
      context: ..
    networks:
      - nightfall_network
    ports:
      - "8546:8546"
