#! /bin/bash

# script to run up the ping pong test on this server

FILE="-f docker-compose.host.docker.internal.yml"

usage()
{
  echo "Usage:"
  echo "  -r or --ropsten; connects to a geth node on ropsten (otherwise localhost)"
  echo "  -h or --help; to print this message"
}
while [ -n "$1" ]; do
  case $1 in
      -h | --help )           usage
                              exit 0
                              ;;
      -r | --ropsten )        FILE="-f docker-compose.ropsten.yml"
                              ;;
      * )                     usage
                              exit 1
    esac
  shift
done
# shut down cleanly in the event of a cntl-c etc. We don't want to leave containers running
trap "exit 1" SIGHUP SIGINT SIGTERM

docker-compose -f docker-compose.yml $FILE up -d --remove-orphans proposer user-local1 user-local2
docker-compose logs -f proposer user-local1 user-local2
