#! /bin/bash

# script to run up the ping pong test on this server

#! /bin/bash

VOLUME_LIST=$(docker volume ls -q)
FILE=

usage()
{
  echo "Usage:"
  echo "  -s or --stubs; runs with circuits stubbed out (faster but no checking of ZKP code)"
  echo "  -h or --help; to print this message"
  echo "  -n or --nightfall; deploy nightfall components to server (nightfall-client, nightfall-optimist, zokrates-worker)"
  echo "  -a or --apps; deploy user, proposer, liquidity provider and challenger apps to the server"
}

# select a Geth or Ganache client
if [ -z "$1" ]; then
  usage
  exit 1
fi
while [ -n "$1" ]; do
  case $1 in
      -n | --nightfall )      FILE="${FILE} -f docker-compose.pong.yml"
                              ;;
      -h | --help )           usage
                              ;;
      -s | --stubs )          FILE="${FILE} -f docker-compose.pong.client.stubs.yml"
                              ;;
      * )                     usage
                              exit 1
    esac
  shift
done
# FILE should always be set.  Asking for -s on its own makes no sense
if [ -z "$FILE" ]; then
  usage
  exit 1
fi
# shut down cleanly in the event of a cntl-c etc. We don't want to leave containers running
trap "exit 1" SIGHUP SIGINT SIGTERM

docker-compose $FILE up -d
docker-compose $FILE logs -f
