#! /bin/bash

# script to run up the ping pong test on this server

FILE="-f docker-compose.host.docker.internal.yml"

usage()
{
  echo "Usage:"
  echo "  -d or --deployer; will also deploy new contracts and do trusted setup"
  echo "  -s or --stubs; will deploy stub circuits"
  echo "  -r or --ropsten; connects to a geth node on ropsten (otherwise localhost)"
  echo "  -h or --help; to print this message"
}
while [ -n "$1" ]; do
  case $1 in
      -h | --help )           usage
                              exit 0
                              ;;
      -d | --deployer )       DEPLOYER="deployer"
                              ;;
      -s | --stubs )          STUBS="-f docker-compose.stubs.yml"
                              ;;
      -r | --ropsten )        FILE="-f docker-compose.ropsten.yml"
                              ;;
      * )                     usage
                              exit 1
    esac
  shift
done
# shut down cleanly in the event of a cntl-c etc. We don't want to leave containers running
trap "exit 1" SIGHUP SIGINT SIGTERM


docker-compose -f docker-compose.yml $FILE $STUBS up -d --remove-orphans client optimist worker $DEPLOYER
docker wait ping-pong_deployer_1

cd ../deploy-contracts
npx truffle migrate --to 2 --network=${ETH_NETWORK}
cd ../ping-pong

docker-compose logs -f
