#! /bin/bash

# script to run up the ping pong test on this server
usage()
{
  echo "Usage:"
  echo "  -g or --ganache; for a ganache simulator. For test purposes"
  echo "  -t or testnet; to use the deployed blockchain client"
  echo "  -s or --stubs; runs with circuits stubbed out (faster but no checking of ZKP code)"
  echo "  -h or --help; to print this message"
}

if [ -z "$1" ]; then
  usage
  exit 1
fi

while [ -n "$1" ]; do
  case $1 in
      -g | --ganache )        FILE="-f docker-compose.yml -f docker-compose.ganache.yml"
                              ;;
      -t | --testnet )        echo "Not implemented yet"
                              exit 1
                              ;;
      -h | --help )           usage
                              ;;
      -s | --stubs )          STUBS="-f docker-compose.deployer.stubs.yml"
                              ;;
      * )                     usage
                              exit 1
    esac
  shift
done
# FILE should always be set.  Asking for -s on its own makes no sense
if [ -z "$FILE" ]; then
  usage
  exit 1
fi
# shut down cleanly in the event of a cntl-c etc. We don't want to leave containers running
trap "exit 1" SIGHUP SIGINT SIGTERM

docker-compose $FILE $STUBS up -d --remove-orphans blockchain1 deployer worker
docker-compose $FILE $STUBS logs -f
