#! /bin/bash
docker-compose down --remove-orphans
docker volume rm nightfall-client_timber-database-volume
docker volume rm nightfall-client_mongodb
docker volume rm nightfall-client_build
docker-compose up
