#! /bin/bash

if [ -f optimist.env ]; then
  grep -v '^#' optimist.env
  # Export env vars
  export $(grep -v '^#' optimist.env | xargs)
fi

VOLUME_LIST=$(docker volume ls -q)
FILE="-f ../docker/docker-compose.optimist.yml"

usage()
{
  echo "Usage:"
  echo "  -r; to remove existing volumes for mongodb and abi contracts"
}

while [ -n "$1" ]; do
  case $1 in
      -r )                          REMOVE_VOLUMES="true"
                                    ;;
      -h  | --help )                usage
                                    ;;
      * )                           usage
                              exit 1
    esac
  shift
done
# FILE should always be set.  Asking for -s on its own makes no sense
if [ -z "$FILE" ]; then
  usage
  exit 1
fi

if [ -n "$REMOVE_VOLUMES" ]; then
  # if-else block checks - volume exist and then removes it.
  if [[ $(echo $VOLUME_LIST | grep nightfall_3_mongodb_optimist_1) ]]; then
    echo -n 'Removing '
    docker volume rm nightfall_3_mongodb_optimist_1
  fi

  if [[ $(echo $VOLUME_LIST | grep nightfall_3_build_optimist_1) ]]; then
    echo -n 'Removing '
    docker volume rm nightfall_3_build_optimist_1
  fi
fi 

echo "docker-compose $FILE -p 'nightfall_3' up -d"
docker-compose $FILE -p 'nightfall_3' up -d
docker-compose -p 'nightfall_3' $FILE logs -f 
