version: '3.5'
# Use this script for running up nightfall_3 with images and applications
services:
  client:
    image: ghcr.io/eyblockchain/nightfall3-client:latest
    build:
      dockerfile: client.Dockerfile
      context: ../
    volumes:
      - type: volume
        source: build
        target: /app/build
      - type: volume
        source: mongodb
        target: /app/mongodb
    networks:
      - pong_network
    depends_on:
      - worker
      - rabbitmq
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      LOG_LEVEL: debug
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      ZOKRATES_WORKER_HOST: worker
      RABBITMQ_HOST: amqp://rabbitmq
      RABBITMQ_PORT: 5672
      TIMBER_HOST: timber
      TIMBER_PORT: 80
      ENABLE_QUEUE: 1
      OPTIMIST_HOST: optimist
      OPTIMIST_PORT: 80
      USE_STUBS: 'false' # make sure this flag is the same as in deployer service
    command: ['npm', 'run', 'dev']

  rabbitmq:
    image: rabbitmq
    networks:
      - pong_network

  optimist:
    image: ghcr.io/eyblockchain/nightfall3-optimist:latest
    build:
      dockerfile: optimist.Dockerfile
      context: ../
    networks:
      - pong_network
    volumes:
      - type: volume
        source: build
        target: /app/build/
    environment:
      WEBSOCKET_PORT: 8080
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546
      HASH_TYPE: mimc
      LOG_LEVEL: debug
      IS_CHALLENGER: 'true'
      TRANSACTIONS_PER_BLOCK: ${TRANSACTIONS_PER_BLOCK:-2}
      TIMBER_HOST: timber
      TIMBER_PORT: 80
    command: ['npm', 'run', 'dev']

  worker:
    image: ghcr.io/eyblockchain/nightfall3-worker:latest
    build:
      dockerfile: worker.Dockerfile
      context: ../
    volumes:
      - type: volume
        source: proving_files
        target: /app/output/
    networks:
      - pong_network
    environment:
      LOG_LEVEL: info

  user-local1:
    image: ghcr.io/eyblockchain/nightfall3-user-local:latest
    build:
      dockerfile: user-local.Dockerfile
      context: ../
    networks:
      - pong_network
    environment:
      OPTIMIST_HOST: optimist
      OPTIMIST_WS_PORT: 8080
      OPTIMIST_HTTP_PORT: 80
      CLIENT_HOST: client
      CLIENT_PORT: 80
      BLOCKCHAIN_WS_HOST: blockchain1
      BLOCKCHAIN_PORT: 8546

volumes:
  mongodb:
  proving_files:
  build:

networks:
  pong_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1
