# name: Browser e2e test
#
# on:
#   pull_request:
#     branch:
#       - master
#
# jobs:
#   e2e-test:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@master
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '14.17.0'
#
#       - name: Start Containers
#         run: |
#           npm ci
#           docker-compose -f docker/compose/docker-compose.dev.yml build
#           ./start-nightfall -g -d -s &> docker-compose.log &disown
#
#       - name: wait 1000s for Containers startup and setup completion
#         run: sleep 1000
#
#       - name: container logs
#         if: always()
#         run: cat docker-compose.log
#
#       - name: Setup proposer
#         run: cd cli && npm ci
#
#       - name: Run proposer
#         run:  |
#           ./proposer > proposer.log &disown
#           sleep 200
#
#       - name: proposer script log
#         if: always()
#         run: cat proposer.log
#
#       - name: Setup browser app
#         run: |
#           cd wallet/
#           npm ci
#
#       - name: Start browser app
#         run: |
#           cd wallet/
#           npm start &> browser-app.log &disown
#           sleep 400
#
#       - name: debug logs - browser startup
#         if: always()
#         run: cat wallet/browser-app.log
#
#       # in local machine
#       # NETWORK_NAME=ganache-nightfall RPC_URL=http://localhost:8546 CHAIN_ID=1337 PRIVATE_KEY=0x4775af73d6dc84a0ae76f8726bda4b9ecf187c377229cb39e1afa7a18236a69e npm run e2e-test
#       - name: Run e2e test
#         run: cd wallet && npm run e2e-test
#         env:
#           NETWORK_NAME: 'ganache-nightfall'
#           RPC_URL: 'http://localhost:8546'
#           CHAIN_ID: 1337
#           PRIVATE_KEY: '0x4775af73d6dc84a0ae76f8726bda4b9ecf187c377229cb39e1afa7a18236a69e'
#
#       - name: test video
#         if: always()
#         uses: actions/upload-artifact@v2
#         with:
#           name: e2e-video
#           path: wallet/tests/e2e/videos/e2e-spec.js.mp4
#
#       - name: debug logs - Container log after e2ee test run
#         if: always()
#         run: cat docker-compose.log
