name: Docker Package

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: $GITHUB_ACTOR

      - name: validate before release
        run: |
          npm ci --no-save
          npm run lint
          npm run lint:md
        env:
          SKIP_PREFLIGHT_CHECK: true
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          CI: true

      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.GPR_BASE_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: semantic release
        uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build and push latest
        run: |
          docker build --build-arg GPR_TOKEN -t $DOCKER_REGISTRY/zokrates-worker/zokrates_worker:latest .
          docker push $DOCKER_REGISTRY/zokrates-worker/zokrates_worker:latest
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          DOCKER_REGISTRY: ${{ secrets.GPR_DOCKER_REGISTRY }}

      - name: docker push versions
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          docker tag $DOCKER_REGISTRY/zokrates-worker/zokrates_worker $DOCKER_REGISTRY/zokrates-worker/zokrates_worker:$VERSION_TAG
          docker tag $DOCKER_REGISTRY/zokrates-worker/zokrates_worker $DOCKER_REGISTRY/zokrates-worker/zokrates_worker:$MAJOR_TAG
          docker push $DOCKER_REGISTRY/zokrates-worker/zokrates_worker:$VERSION_TAG
          docker push $DOCKER_REGISTRY/zokrates-worker/zokrates_worker:$MAJOR_TAG
        env:
          DOCKER_REGISTRY: ${{ secrets.GPR_DOCKER_REGISTRY }}
          VERSION_TAG: v${{ steps.semantic.outputs.release-version }}
          MAJOR_TAG: v${{ steps.semantic.outputs.release-major }}
