name: "test one"
on:
  push:
    branch:
      - liju.jose/configure-hosted-geth-for-blockchain-client-2

jobs:
  testnet-test:
    runs-on: ubuntu-18.04
    environment: TESTNET_DEPLOYMENT
    env:
      ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
      INFURA_PROJECT_SECRET: ${{ secrets.INFURA_PROJECT_SECRET }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'

      - name: Start Containers
        run: |
          docker-compose build
          ./start-nightfall -r &> testnet-test.log &disown

      # - name: wait 2000s for Containers startup and setup completion
      #   run: sleep 2000

      # kept it for future debug
      - run: sleep 1000
      - name: debug logs - after container startup 1
        if: always()
        run: cat testnet-test.log

      - run: sleep 6000
      - name: debug logs - after container startup 2
        if: always()
        run: cat testnet-test.log

      - name: Run integration test
        run: |
          npm ci
          npm run hosted-geth-test

      - name: debug logs - after integration test run
        if: always()
        run: cat testnet-test.log

      - name: If integration test failed, shutdown the Containers
        if: failure()
        run: docker-compose down -v

      - name: If integration test failed, upload logs files as artifacts
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: testnet-test-logs
          path: ./testnet-test.log
